version: '3.8'
services:
  php-apache-environment:
    image: dillahani/php-uas-dila
    container_name: php-apache
    volumes:
      - ./php/src:/var/www/html/
    ports:
      - 80:80
    networks:
      - backend

networks:
  backend:
    name: backend-network
    ipam:
      driver: default
      config:
        - subnet: 172.88.0.0/24